[project]
name = "bugzilla-mcp"
version = "0.1.0"
description = "An MCP Server for Bugzilla json rpc api"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.7",
    "pydantic-settings>=2.0.0",
]
